name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Slack notify start
        uses: act10ns/slack@v2.1.0
        id: slack-start
        with:
          channel: '#workflows'
          status: starting
          message: 'Cypress tests are starting...'
        if: always()

      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4.2.2
      
      - name: Set up Node.js
        id: setup-node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '16'

      - name: Install dependencies
        id: install-deps
        run: npm ci

      - name: Run Cypress tests
        id: run-cypress
        run: npx cypress run --browser chrome

      - name: Upload mochawesome reports
        id: upload-reports
        uses: actions/upload-artifact@v4.6.2
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome
          if-no-files-found: warn
          retention-days: 7
            
      - name: Set git user for deployment
        run: |
          git config --global user.email "nkereuwem.udoudo1@gmail.com"
          git config --global user.name "Nkereuwem03"

      - name: Deploy Mochawesome Report to GitHub Pages
        id: deploy-report
        if: success()
        run: npm run deploy-report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack notify end
        id: slack-end
        uses: act10ns/slack@v2.1.0
        with:
          channel: '#workflows'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()

      - name: Notify completion and clean up 
        id: notify-completion
        run: |
          echo "Cypress tests completed with status: ${{ job.status }}"
          if [ "${{ job.status }}" == "success" ]; then
            echo "Cypress tests passed successfully."
          elif [ "${{ job.status }}" == "failure" ]; then
            echo "Cypress tests failed. Please check the logs and reports."
          elif [ "${{ job.status }}" == "skipped" ]; then
            echo "Cypress tests were skipped."
          elif [ "${{ job.status }}" == "cancelled" ]; then
            echo "Cypress tests were cancelled."
          fi
          echo "Cleaning up reports and artifacts..."
          # rm -rf cypress/reports/mochawesome
          # rm -rf cypress/screenshots
          # rm -rf cypress/videos
          echo "Cleaned up reports and artifacts."